name: LiteWaffle-Template
main: io.github.patrick.sample.plugin.SamplePlugin
version: 1.0
description: LiteWaffle-Template
author: SapoKR
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.31
depend:
  - LiteWaffle